BoardApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.urls import include
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeDoneView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Boards.urls')),
    path('account/', include('accounts.urls')),
    path('account/reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
            name='password_reset_confirm'),
    path('reset/complete/', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('settings/password/done/', PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),
]

Boards/urls.py
from django.urls import path
from django.urls import re_path
from . import views


app_name = 'Boards'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'^(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board'),
    re_path(r'^(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    re_path(r'^(?P<board_pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_view'),
    re_path(r'^(?P<board_pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.topic_reply, name='topic_reply'),
    re_path(r'^(?P<board_pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$', views.EditPost.as_view(),
            name='edit_post'),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordChangeView
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('reset/', PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
    ), name='password_reset'),
    path('settings/password/', PasswordChangeView.as_view(template_name='accounts/password_change.html'),
         name='password_change'),
    path('settings/', views.UpdateUserProfile.as_view(), name='myaccount'),
]

Boards/models.py
import math

from django.db import models
from django.contrib.auth.models import User

from django.utils.html import mark_safe
from markdown import markdown


# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=30,unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255, unique=True)
    last_updated = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)

    # Foreign Keys
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics',)
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='topics',)

    def __str__(self):
        return '%s : %s' % (self.board.__str__(), self.subject,)

    def get_page_count(self):
        count = self.posts.count()
        pages = count / 2
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 6

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)

    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:10]


class Post(models.Model):
    message = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)

    # Foreign Keys
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts',)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='+')

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

    def __str__(self):
        return '%s : %s' % (self.topic.__str__(), self.message,)

Boards/forms.py
from django import forms
from .models import Topic
from .models import Post


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'rows': 5,
                'placeholder': 'What is on your mind?',
            }
        ),
        max_length=4000,
        help_text='The maximum length of the text is 4000.'
    )

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

Boards/views.py
from django.shortcuts import render
from django.shortcuts import reverse
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.views.generic import UpdateView
from django.views.generic import ListView
from django.utils import timezone
from django.utils.decorators import method_decorator

from .models import Board
from .models import Topic
from .models import Post
from .forms import NewTopicForm
from .forms import PostForm


class IndexView(ListView):
    model = Board
    template_name = 'Boards/index.html'
    context_object_name = 'boards'


class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'Boards/topics.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset


class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'Boards/topic_posts.html'
    paginate_by = 2

    def get_context_data(self, **kwargs):

        session_key = 'viewed_topic_{}'.format(self.topic.pk)
        if not self.request.session.get(session_key, False):
            self.topic.views += 1
            self.topic.save()
            self.request.session[session_key] = True

        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, board__pk=self.kwargs.get('board_pk'), pk=self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset


@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    user = request.user

    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=user
            )
            return redirect('Boards:board', pk=board.pk)
    else:
        form = NewTopicForm()
    return render(request, 'Boards/new-topic.html', {'board': board, 'form': form})


@login_required
def topic_reply(request, board_pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=board_pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()

            topic.last_updated = timezone.now()
            topic.save()

            topic_url = reverse('Boards:topic_view', kwargs={'board_pk': board_pk, 'topic_pk': topic_pk})
            topic_post_url = '{url}?page={page}#{id}'.format(
                url=topic_url,
                id=post.pk,
                page=topic.get_page_count()
            )

            return redirect(topic_post_url)
    else:
        form = PostForm()
    return render(request, 'Boards/reply_topic.html', {'topic': topic, 'form': form})


@method_decorator(login_required, name='dispatch')
class EditPost(UpdateView):

    model = Post
    fields = ('message',)
    template_name = 'Boards/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()

        return redirect('Boards:topic_view', board_pk=post.topic.board.pk, topic_pk=post.topic.pk)

Boards/templates/Boards/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
        <title>{% block title %}Django Boards{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'Boards/css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
  {% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'Boards:index' %}">Django Boards</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="#">My account</a>
              <a class="dropdown-item" href="#">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
            </div>
          </li>
        </ul>
      {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}
    </div>
      </div>
    </nav>
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
      {% endblock body %}
      <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block javascript %}{% endblock %}
    </div>
  </body>
</html>

Boards/templates/Boards/edit_post.html
{% extends 'Boards/base.html' %}

{% block title %} Edit Post {% endblock %}

{% block stylesheet %}
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'Boards:index' %}">Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'Boards:board' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
<li class="breadcrumb-item"><a href="{% url 'Boards:topic_view' post.topic.board.pk post.topic.pk %}">
  {{ post.topic.subject }} </a> </li>
<li class="breadcrumb-item active">Edit Post</li>
{% endblock %}

{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'Boards:topic_view' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

{% block javascript %}
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

Boards/templates/Boards/index.html
{% extends 'Boards/base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="{% url 'Boards:board' board.pk %}"> {{ board.name }} </a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">{{ board.get_posts_count }}</td>
              <td class="align-middle">{{ board.topics.count }}</td>
              <td>
                  {% with post=board.get_last_post %}
                  {% if post %}
    <small>
      <a href="{% url 'Boards:topic_view' board.pk post.topic.pk %}">
        By {{ post.created_by.username }} at {{ post.created_at }}
      </a>
    </small>
  {% else %}
    <small class="text-muted">
      <em>No posts yet.</em>
    </small>
  {% endif %}
            {% endwith %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}

Boards/templates/Boards/new-topic.html
{% extends 'Boards/base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'Boards:index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'Boards:board' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}

<form method="post" novalidate>
  {% csrf_token %}
  {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

Boards/templates/Boards/reply_topic.html
{% extends 'Boards/base.html' %}

{% block title %} Post a reply {% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'Boards:index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'Boards:board' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'Boards:topic_view' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>
  <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block content %}

  <form method="post" class="mb-4">
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post a reply</button>
  </form>

  {% for post in topic.get_last_ten_posts %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created_at }}</small>
          </div>
        </div>
        {{ post.message }}
      </div>
    </div>
  {% endfor %}

{% endblock %}

Boards/templates/Boards/topic_posts.html
{% extends 'Boards/base.html' %}

{% load static %}

{% load gravatar %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block stylesheet %}
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'Boards:index' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'Boards:board' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}

  <div class="mb-4">
    <a href="{% url 'Boards:topic_reply' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
  </div>

  {% for post in posts %}
    <div id="{{ post.pk }}" class="card
    {% if forloop.last %}mb-4{% else %}mb-2{% endif %}
    {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
      <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
    {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{{ post.created_by|gravatar }}" alt="{{ post.created_by.username }}" class="w-100">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
            </div>
            {{ post.get_message_as_markdown }}
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'Boards:edit_post' topic.board.pk topic.pk post.pk %}" class="btn btn-primary btn-sm"
                   role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{% include 'includes/pagination.html' %}

{% endblock %}

{% block javascript %}
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

Boards/templates/Boards/topics.html
{% extends 'Boards/base.html' %}

{% load humanize %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'Boards:index' %}"> Boards </a></li>
<li class="breadcrumb-item active">{{ board.name }}</li>

{% endblock %}

{% block content %}

<div class="mb-4">
    <a href="{% url 'Boards:new_topic' board.pk %}" class="btn btn-primary">New topic</a>
  </div>

<table class="table table-striped mb-4">
    <thead class="thead-dark">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
        <tr>
            <td>
                <p class="mb-0">
                <a href="{% url 'Boards:topic_view' board_pk=board.pk topic_pk=topic.pk %}">{{ topic.subject }}</a>
                </p>
                <small class="text-muted">
              Pages:
              {% for i in topic.get_page_range %}
                    {% if not forloop.first %}
                    ,
                    {% endif %}
                <a href="{% url 'Boards:topic_view' board.pk topic.pk %}?page={{ i }}">{{ i }}</a>
              {% endfor %}
              {% if topic.has_many_pages %}
              ... <a href="{% url 'Boards:topic_view' board.pk topic.pk %}?page={{ topic.get_page_count }}">Last Page</a>
              {% endif %}
            </small>
            </td>
          <td>{{ topic.starter.username }}</td>
          <td>{{ topic.replies }}</td>
          <td>{{ topic.views }}</td>
          <td>{{ topic.last_updated|naturaltime }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% include 'includes/pagination.html' %}

{% endblock %}